### ISSUE TITLE
Debugging instruction in production

### ISSUE THREAD

**Issue by chloeavoustin** [wide/modulus#8]
The use of modulus and its modules adds a lot of debugging instructions in production. Using modulus and its modules adds a lot of debugging instructions in production. 

Maybe we should use the logger function and add a boolean to condition the display.

**Comment by robiseb** [comment]
Hello @chloeavoustin 
Thank you for using Modulus and bringing us some improvements requests.

This require was planned on the roadmap in Q1 and should arrive in february.

Please don't hesitate to open other issues or merge requests if you are comfortable with Modulus.

Best regards

**Comment by robiseb** [comment]
Hello @chloeavoustin ,

Your request has been developed and will be added soon to the next release.

See more informations here: #12
