### ISSUE TITLE
Custom settings on the [data-call] attribute

### ISSUE THREAD

**Issue by jdacosta** [wide/modulus#9]
It would be nice to be able to pass custom parameters in the [data-call.params]. 

Today we are limited to `$el`, and `$event` but I may potentially need to pass a value.

Also, think about being able to pass multiple parameters: e.g. : 
``` <button data-call=“foo#bar.beer" data-call.params=“$el,'Le Trou du Diable Saison du Tracteur'">Give me that beer !</button>```

**Comment by robiseb** [comment]
Hello @jdacosta ,

Your request has been developed and will be added to the next release.  
**Note that it comes with a breaking change.**

See more informations here: #11
